source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-default-layout"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-include-cache"
  gem "jekyll-remote-theme"
end

gem "base64"
gem "csv"

gem "jekyll-github-metadata", ">= 2.15"

gem "html-proofer", "~> 5.0", :group => :development
